apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: backend
    port: {{ .Values.port }}
  selector:
    app: {{ .Release.Name }}
