apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
{{ toYaml .Values.labels | indent 4 }}
data:
  main.yaml: |-
    logLevel: "{{ .Values.logLevel }}"
    targetLabels:
{{ toYaml .Values.targetLabels | indent 6 }}
    port: {{ .Values.port }}
    prometheus:
{{ toYaml .Values.prometheus | indent 6 }}
