environments:
  ci:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: polkadot-base-services
  chart: w3f/polkadot-base-services
  version: v0.27.2
  values:
  - ./config/polkadot-base-services.yaml.gotmpl

- name: polkadot-1
  chart: w3f/polkadot
  version: v0.27.2
  values:
  - ./config/polkadot.yaml.gotmpl
  - name: polkadot-1
    p2pPort: 30333
    validator: true
    extraArgs:
      validator: "--alice"
    nodeKey: "0000000000000000000000000000000000000000000000000000000000000000"

- name: polkadot-2
  chart: w3f/polkadot
  version: v0.27.2
  values:
  - ./config/polkadot.yaml.gotmpl
  - name: polkadot-2
    p2pPort: 30334
    extraBootnodes:
    - "/dns4/polkadot-1-p2p/tcp/30333/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN"
- name: polkadot-3
  chart: w3f/polkadot
  version: v0.27.2
  values:
  - ./config/polkadot.yaml.gotmpl
  - name: polkadot-3
    p2pPort: 30335
    extraBootnodes:
    - "/dns4/polkadot-1-p2p/tcp/30333/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN"

- name: polkadot-4
  chart: w3f/polkadot
  version: v0.27.2
  values:
  - ./config/polkadot.yaml.gotmpl
  - name: polkadot-4
    p2pPort: 30336
    extraBootnodes:
    - "/dns4/polkadot-1-p2p/tcp/30333/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN"
